# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decode_pedals_gui.ui'
#
# Created: Fri Jan 16 11:35:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_decodePedals(object):
    def setupUi(self, decodePedals):
        decodePedals.setObjectName(_fromUtf8("decodePedals"))
        decodePedals.resize(921, 784)
        self.centralwidget = QtGui.QWidget(decodePedals)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.buttonOpen = QtGui.QPushButton(self.centralwidget)
        self.buttonOpen.setGeometry(QtCore.QRect(0, 2, 81, 24))
        self.buttonOpen.setObjectName(_fromUtf8("buttonOpen"))
        self.buttonExit = QtGui.QPushButton(self.centralwidget)
        self.buttonExit.setGeometry(QtCore.QRect(0, 58, 81, 24))
        self.buttonExit.setObjectName(_fromUtf8("buttonExit"))
        self.buttonSave = QtGui.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(0, 30, 81, 24))
        self.buttonSave.setObjectName(_fromUtf8("buttonSave"))
        self.normCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.normCheckBox.setGeometry(QtCore.QRect(10, 490, 111, 21))
        self.normCheckBox.setObjectName(_fromUtf8("normCheckBox"))
        self.infoTableView = QtGui.QTableView(self.centralwidget)
        self.infoTableView.setGeometry(QtCore.QRect(220, 0, 661, 571))
        self.infoTableView.setObjectName(_fromUtf8("infoTableView"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 100, 41, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 100, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.buttonPlot = QtGui.QPushButton(self.centralwidget)
        self.buttonPlot.setGeometry(QtCore.QRect(130, 410, 51, 24))
        self.buttonPlot.setObjectName(_fromUtf8("buttonPlot"))
        self.checkBoxLP = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxLP.setGeometry(QtCore.QRect(10, 370, 91, 31))
        self.checkBoxLP.setObjectName(_fromUtf8("checkBoxLP"))
        self.checkBoxRP = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxRP.setGeometry(QtCore.QRect(10, 390, 101, 31))
        self.checkBoxRP.setObjectName(_fromUtf8("checkBoxRP"))
        self.checkBoxLS = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxLS.setGeometry(QtCore.QRect(10, 410, 81, 31))
        self.checkBoxLS.setObjectName(_fromUtf8("checkBoxLS"))
        self.checkBoxRS = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxRS.setGeometry(QtCore.QRect(10, 430, 91, 31))
        self.checkBoxRS.setObjectName(_fromUtf8("checkBoxRS"))
        self.rightMaxFile = QtGui.QLabel(self.centralwidget)
        self.rightMaxFile.setGeometry(QtCore.QRect(150, 130, 41, 20))
        self.rightMaxFile.setFrameShape(QtGui.QFrame.Box)
        self.rightMaxFile.setObjectName(_fromUtf8("rightMaxFile"))
        self.leftMaxFile = QtGui.QLabel(self.centralwidget)
        self.leftMaxFile.setGeometry(QtCore.QRect(70, 130, 41, 20))
        self.leftMaxFile.setFrameShape(QtGui.QFrame.Box)
        self.leftMaxFile.setFrameShadow(QtGui.QFrame.Plain)
        self.leftMaxFile.setObjectName(_fromUtf8("leftMaxFile"))
        self.numRowsVal = QtGui.QLabel(self.centralwidget)
        self.numRowsVal.setGeometry(QtCore.QRect(80, 290, 91, 20))
        self.numRowsVal.setFrameShape(QtGui.QFrame.Box)
        self.numRowsVal.setObjectName(_fromUtf8("numRowsVal"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 41, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 31, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 31, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.leftOff = QtGui.QLabel(self.centralwidget)
        self.leftOff.setGeometry(QtCore.QRect(70, 210, 41, 20))
        self.leftOff.setFrameShape(QtGui.QFrame.Box)
        self.leftOff.setFrameShadow(QtGui.QFrame.Plain)
        self.leftOff.setObjectName(_fromUtf8("leftOff"))
        self.rightOff = QtGui.QLabel(self.centralwidget)
        self.rightOff.setGeometry(QtCore.QRect(150, 210, 41, 20))
        self.rightOff.setFrameShape(QtGui.QFrame.Box)
        self.rightOff.setObjectName(_fromUtf8("rightOff"))
        self.leftOn = QtGui.QLabel(self.centralwidget)
        self.leftOn.setGeometry(QtCore.QRect(70, 250, 41, 20))
        self.leftOn.setFrameShape(QtGui.QFrame.Box)
        self.leftOn.setFrameShadow(QtGui.QFrame.Plain)
        self.leftOn.setObjectName(_fromUtf8("leftOn"))
        self.rightOn = QtGui.QLabel(self.centralwidget)
        self.rightOn.setGeometry(QtCore.QRect(150, 250, 41, 20))
        self.rightOn.setFrameShape(QtGui.QFrame.Box)
        self.rightOn.setObjectName(_fromUtf8("rightOn"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 41, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.leftMaxPedal = QtGui.QLabel(self.centralwidget)
        self.leftMaxPedal.setGeometry(QtCore.QRect(70, 170, 41, 20))
        self.leftMaxPedal.setFrameShape(QtGui.QFrame.Box)
        self.leftMaxPedal.setFrameShadow(QtGui.QFrame.Plain)
        self.leftMaxPedal.setObjectName(_fromUtf8("leftMaxPedal"))
        self.rightMaxPedal = QtGui.QLabel(self.centralwidget)
        self.rightMaxPedal.setGeometry(QtCore.QRect(150, 170, 41, 20))
        self.rightMaxPedal.setFrameShape(QtGui.QFrame.Box)
        self.rightMaxPedal.setObjectName(_fromUtf8("rightMaxPedal"))
        self.checkBoxKbd = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxKbd.setGeometry(QtCore.QRect(10, 450, 91, 31))
        self.checkBoxKbd.setObjectName(_fromUtf8("checkBoxKbd"))
        self.infoBox = QtGui.QTextEdit(self.centralwidget)
        self.infoBox.setGeometry(QtCore.QRect(220, 580, 661, 151))
        self.infoBox.setObjectName(_fromUtf8("infoBox"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(95, 4, 120, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioVersion1 = QtGui.QRadioButton(self.groupBox)
        self.radioVersion1.setGeometry(QtCore.QRect(15, 24, 97, 21))
        self.radioVersion1.setChecked(True)
        self.radioVersion1.setObjectName(_fromUtf8("radioVersion1"))
        self.radioVersion2 = QtGui.QRadioButton(self.groupBox)
        self.radioVersion2.setGeometry(QtCore.QRect(15, 48, 97, 21))
        self.radioVersion2.setObjectName(_fromUtf8("radioVersion2"))
        decodePedals.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(decodePedals)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Data = QtGui.QMenu(self.menubar)
        self.menu_Data.setObjectName(_fromUtf8("menu_Data"))
        self.menu_Plot = QtGui.QMenu(self.menubar)
        self.menu_Plot.setObjectName(_fromUtf8("menu_Plot"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        decodePedals.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(decodePedals)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        decodePedals.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(decodePedals)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(decodePedals)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNormalise = QtGui.QAction(decodePedals)
        self.actionNormalise.setObjectName(_fromUtf8("actionNormalise"))
        self.actionAll = QtGui.QAction(decodePedals)
        self.actionAll.setObjectName(_fromUtf8("actionAll"))
        self.actionLeft_Pos = QtGui.QAction(decodePedals)
        self.actionLeft_Pos.setObjectName(_fromUtf8("actionLeft_Pos"))
        self.actionRight_Pos = QtGui.QAction(decodePedals)
        self.actionRight_Pos.setObjectName(_fromUtf8("actionRight_Pos"))
        self.actionLeft_Sw = QtGui.QAction(decodePedals)
        self.actionLeft_Sw.setObjectName(_fromUtf8("actionLeft_Sw"))
        self.actionRight_Sw = QtGui.QAction(decodePedals)
        self.actionRight_Sw.setObjectName(_fromUtf8("actionRight_Sw"))
        self.actionExit = QtGui.QAction(decodePedals)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCase_1 = QtGui.QAction(decodePedals)
        self.actionCase_1.setObjectName(_fromUtf8("actionCase_1"))
        self.actionCase_2 = QtGui.QAction(decodePedals)
        self.actionCase_2.setObjectName(_fromUtf8("actionCase_2"))
        self.actionCase_3 = QtGui.QAction(decodePedals)
        self.actionCase_3.setObjectName(_fromUtf8("actionCase_3"))
        self.actionCase_4 = QtGui.QAction(decodePedals)
        self.actionCase_4.setObjectName(_fromUtf8("actionCase_4"))
        self.menu_File.addAction(self.actionLoad)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Data.addAction(self.actionNormalise)
        self.menu_Plot.addAction(self.actionAll)
        self.menu_Plot.addAction(self.actionLeft_Pos)
        self.menu_Plot.addAction(self.actionRight_Pos)
        self.menu_Plot.addAction(self.actionLeft_Sw)
        self.menu_Plot.addAction(self.actionRight_Sw)
        self.menuAnalyse.addAction(self.actionCase_1)
        self.menuAnalyse.addAction(self.actionCase_2)
        self.menuAnalyse.addAction(self.actionCase_3)
        self.menuAnalyse.addAction(self.actionCase_4)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Data.menuAction())
        self.menubar.addAction(self.menu_Plot.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())

        self.retranslateUi(decodePedals)
        QtCore.QObject.connect(self.buttonExit, QtCore.SIGNAL(_fromUtf8("clicked()")), decodePedals.close)
        QtCore.QMetaObject.connectSlotsByName(decodePedals)

    def retranslateUi(self, decodePedals):
        decodePedals.setWindowTitle(_translate("decodePedals", "MainWindow", None))
        self.buttonOpen.setText(_translate("decodePedals", "Open", None))
        self.buttonExit.setText(_translate("decodePedals", "Close", None))
        self.buttonSave.setText(_translate("decodePedals", "Save", None))
        self.normCheckBox.setToolTip(_translate("decodePedals", "<html><head/><body><p>Set maximums to 100</p></body></html>", None))
        self.normCheckBox.setText(_translate("decodePedals", "Normalise", None))
        self.label.setText(_translate("decodePedals", "Left", None))
        self.label_2.setText(_translate("decodePedals", "Right", None))
        self.label_3.setText(_translate("decodePedals", "Rows", None))
        self.buttonPlot.setText(_translate("decodePedals", "Plot", None))
        self.checkBoxLP.setText(_translate("decodePedals", "Left Pos", None))
        self.checkBoxRP.setText(_translate("decodePedals", "Right Pos", None))
        self.checkBoxLS.setText(_translate("decodePedals", "Left Sw", None))
        self.checkBoxRS.setText(_translate("decodePedals", "Right Sw", None))
        self.rightMaxFile.setText(_translate("decodePedals", "TextLabel", None))
        self.leftMaxFile.setText(_translate("decodePedals", "TextLabel", None))
        self.numRowsVal.setText(_translate("decodePedals", "TextLabel", None))
        self.label_4.setText(_translate("decodePedals", "FMax", None))
        self.label_5.setText(_translate("decodePedals", "Off", None))
        self.label_6.setText(_translate("decodePedals", "On", None))
        self.leftOff.setText(_translate("decodePedals", "TextLabel", None))
        self.rightOff.setText(_translate("decodePedals", "TextLabel", None))
        self.leftOn.setText(_translate("decodePedals", "TextLabel", None))
        self.rightOn.setText(_translate("decodePedals", "TextLabel", None))
        self.label_7.setText(_translate("decodePedals", "PMax", None))
        self.leftMaxPedal.setText(_translate("decodePedals", "TextLabel", None))
        self.rightMaxPedal.setText(_translate("decodePedals", "TextLabel", None))
        self.checkBoxKbd.setText(_translate("decodePedals", "Key", None))
        self.groupBox.setTitle(_translate("decodePedals", "Data Version", None))
        self.radioVersion1.setToolTip(_translate("decodePedals", "Pedals with microswitch", None))
        self.radioVersion1.setText(_translate("decodePedals", "V1", None))
        self.radioVersion2.setToolTip(_translate("decodePedals", "Pedals without microswqitch", None))
        self.radioVersion2.setText(_translate("decodePedals", "V2", None))
        self.menu_File.setTitle(_translate("decodePedals", "&File", None))
        self.menu_Data.setTitle(_translate("decodePedals", "&Data", None))
        self.menu_Plot.setTitle(_translate("decodePedals", "&Plot", None))
        self.menuAnalyse.setTitle(_translate("decodePedals", "Analyse", None))
        self.actionLoad.setText(_translate("decodePedals", "Open", None))
        self.actionSave.setText(_translate("decodePedals", "Save", None))
        self.actionNormalise.setText(_translate("decodePedals", "Normalise", None))
        self.actionAll.setText(_translate("decodePedals", "All", None))
        self.actionLeft_Pos.setText(_translate("decodePedals", "Left Pos", None))
        self.actionRight_Pos.setText(_translate("decodePedals", "Right Pos", None))
        self.actionLeft_Sw.setText(_translate("decodePedals", "Left Sw", None))
        self.actionRight_Sw.setText(_translate("decodePedals", "Right Sw", None))
        self.actionExit.setText(_translate("decodePedals", "Exit", None))
        self.actionCase_1.setText(_translate("decodePedals", "case 1", None))
        self.actionCase_2.setText(_translate("decodePedals", "case 2", None))
        self.actionCase_3.setText(_translate("decodePedals", "case 3", None))
        self.actionCase_4.setText(_translate("decodePedals", "case 4", None))

